build: clean
	javac -d WEB-INF/classes/ src/Product.java
	javac -d WEB-INF/classes/ src/Category.java
	javac -d WEB-INF/classes/ src/DataHelper.java
	javac -d WEB-INF/classes/ src/*Servlet.java

clean:
	rm -rf WEB-INF/classes/*
