
build: clean
	javac -d WEB-INF/classes/ src/Database.java
	javac -d WEB-INF/classes/ src/Category.java
	javac -d WEB-INF/classes/ src/Product.java
	javac -d WEB-INF/classes/ src/DataHelper.java
	javac -d WEB-INF/classes/ src/ProductResource.java
	javac -d WEB-INF/classes/ src/OrderResource.java

clean:
	rm -rf WEB-INF/classes/*
